# Github actions for web deployment

name: Web Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        run: echo "Hello World"
      - name: Notify Slack
        uses: act10ns/slack@v2
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          webhook-url: "https://hooks.slack.com/services/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"
        if: always()
