# Github actions for web deployment

name: Web Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Say Hello World
        run: echo "Hello World" > hello.txt cat hrllo.txt
      - name: Notify Slack
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          run: |
            echo "Setting up ENV variables for message:"
            echo "SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL"
            echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
            if [ "${{ github.ref }}" = "refs/heads/master" ]; then
              SLACK_COLOR="#36a64f"
              SLACK_TITLE="Deployment to Production"
            else
              SLACK_COLOR="#f9a41b"
              SLACK_TITLE="Deployment to Staging"
            fi
          message: ${{ format('{0} is {1}', env.SLACK_TITLE, job.status) }}
        if: always()
