# Github actions for web deployment

name: Web Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Say Hello World
        run: echo "Hello World" > hello.txt cat hrllo.txt
      - name: Slack Notification set Env
        id: slack_env
        run: |
          if [ ${{ github.ref }} == "refs/heads/main" ]; then
            echo "::set-output name=slackMessage::Deployed to Production"
            echo "::set-output name=slackEmoji:::rocket:"
          else
            echo "::set-output name=slackMessage::Deployed to Staging"
            echo "::set-output name=slackEmoji:::x:"
          fi
      - name: Notify Slack
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          message: ${{ format('{0} {1}', steps.slack_env.outputs.slackEmoji, steps.slack_env.outputs.slackMessage) }}
        if: always()
