# Github actions for web deployment

name: Web Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Say Hello World
        run: echo "Hello World" > hello.txt cat hrllo.txt
      - name: Notify Slack
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          run: |
            if [ ${{ github.ref }} == "refs/heads/main" ]; then
              message: ${{ github.actor }} deployed {{ env.GITHUB_REF_NAME }} branch to production
            else
              message: ${{ github.actor }} deployed {{ env.GITHUB_REF_NAME }} branch to staging
            fi
        if: always()
