# Github actions for web deployment

name: Web Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Say Hello World
        run: echo "Hello World" > hello.txt cat hrllo.txt
      - name: Notify Slack
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          message: ${{ github.ref == 'refs/heads/main' && format('{0} deployed to {1} to production', github.actor, github.ref) || format('{0} deployed to {1} to staging', github.actor, github.ref) }}
        if: always()
